#!/usr/bin/env node
const chalk = require("chalk")
console.log(`${chalk.bgBlue.bold(' * * * * * * * * ')}${chalk.bgRed('                                                      ')}`)
console.log(`${chalk.bgBlue.bold(' * * * * * * * * ')}${chalk.bgWhite('                                                      ')}`)
console.log(`${chalk.bgBlue.bold(' * * * * * * * * ')}${chalk.bgRed('                                                      ')}`)
console.log(`${chalk.bgBlue.bold(' * * * * * * * * ')}${chalk.bgWhite('                                                      ')}`)
console.log(`${chalk.bgBlue.bold(' * * * * * * * * ')}${chalk.bgRed('                                                      ')}`)
console.log(`${chalk.bgBlue.bold(' * * * * * * * * ')}${chalk.bgWhite('                                                      ')}`)
console.log(`${chalk.bgBlue.bold(' * * * * * * * * ')}${chalk.bgRed('                                                      ')}`)
console.log(`${chalk.bgWhite('                                                                       ')}`)
console.log(`${chalk.bgRed('                                                                       ')}`)
console.log(`${chalk.bgWhite('                                                                       ')}`)
console.log(`${chalk.bgRed('                                                                       ')}`)
console.log(`${chalk.bgWhite('                                                                       ')}`)
console.log(`${chalk.bgRed('                                                                       ')}`)
